# TODO: slimだと上手くいかない可能性あり
FROM rust:1.70.0-bullseye
RUN apt-get -y update
RUN apt-get -y install git sudo wget curl vim zsh nano

RUN chsh -s /bin/zsh

RUN mkdir -p /root/.atcodertools/template
RUN mkdir -p /root/atcoder-workspace

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# TODO: ACL, rust-analyzerの導入
RUN cargo install cargo-compete --locked
RUN rustup component add rustfmt

ARG shell_rc="/root/.zshrc"
RUN echo 'alias cnew="python3 /workspaces/atcoder/add_to_setting_json.py"' >> ${shell_rc}
RUN echo 'alias ctest="cargo compete test"' >> ${shell_rc}
RUN echo 'alias csub="cargo compete submit"' >> ${shell_rc}


# Oh my zshのテーマを変更
# (anon):12: character not in range
# が出力され上手くいかないのでコメントアウト
# RUN sed -i.bak 's/^ZSH_THEME="[^"]*"/ZSH_THEME="agnoster"/' ~/.zshrc


CMD ["/bin/zsh"]