name: "Fail merging test"
on:
  workflow_dispatch:

jobs:
  send-string:
    runs-on: ubuntu-latest
    outputs:
      send-string: ${{ steps.send-string.outputs.send-string }}
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0