name: "Send string, reveive and display it"
on:
  workflow_dispatch:

jobs:
  send-string:
    runs-on: ubuntu-latest
    outputs:
      send-string: ${{ steps.send-string.outputs.send-string }}
    steps:
      - name: Output changed files
        id: send-string
        run: echo "send-string=hello" >> $GITHUB_OUTPUT

  receive-string:
    runs-on: ubuntu-latest
    needs: send-string
    steps:
      - name: Display receive string
        run: echo ${{ needs.job1.outputs.send-string }}
