name: "Test workflow commands"
on:
  workflow_dispatch:

jobs:
  test-workflow-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Output message(debug)
        run: echo "::debug::Set the Octocat variable"
      - name: Output message(notice)
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Output message(warning)
        run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Output message(error)
        run: echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Output message(without parameter)
        run: echo "::error file=,line=,col=,endColumn=::Missing semicolon"
