name: "Test workflow commands"
on:
  workflow_dispatch:

jobs:
  test-workflow-commands:
    runs-on: ubuntu-latest
    # outputs:
    #   send-string: ${{ steps.send-string.outputs.send-string }}
    steps:
      - name: Output annotation(notice)
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Output annotation(warning)
        run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Output annotation(error)
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
